services:
  - type: web
    name: essay-bot
    runtime: python
    buildCommand: ""
    startCommand: python main.py
    plan: free
    region: oregon
    autoDeploy: true
    repo: https://github.com/vladislav777666/Essay_bot
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
