services:
  - type: web
    name: essay-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    build:
  environment:
    PYTHON_VERSION: 3.11

